@startuml
skinparam class {
    BackgroundColor Snow
    BorderColor Black
    FontName Arial
    FontColor Black
    FontStyle Normal
    ArrowThickness 1
}
skinparam linetype ortho
!define RECTANGLE class


' RECTANGLE FastAPI {
' }

RECTANGLE LibraryControl {
    + 
}

RECTANGLE PlaygroundControl {

    + create_playground(playground_id: str, playground_name: str, 
    playground_description: str): Playground
    + delete_playground(playground_id: str): None
    + update_playground(playground_id: str, playground_name: str, playground_description: str, 
    playground_models: List[str], playground_chain: List[str]): None
    + list_playgrounds(): List[str]
    + run_playground(playground_id: str): None
    + stop_playground(playground_id: str): None
    + add_model_to_playground(playground_id: str, model_id: str): None
    + add_chain_to_playground(playground_id: str, chain_id: str): None
}

RECTANGLE ModelControl {
    - active_models: List[Dict[str, Any]]
    - hardware_preference: str
    - LibraryControl: LibraryControl
    __init__()
    + download_model(model_id: str): bool
    + load_model(model_id: str): bool
    + unload_model(model_id: str): bool
    + inference(model_id: str, request_payload: Any): Any
    + list_active_models(): List[str]
    + delete_model(model_id: str): bool
    - _get_model_class(model_source: str): Type
}

RECTANGLE TransformerModel {
    - model_id: str
    - model: Any
    - tokenizer: Any
    - processor: Any
    __init__(model_id: str)
    + download(model_id: str): None
    + load(model_id: str): None
    + inference(request_payload: Any): Any
    + train(data_path: str, epochs: int = 100): Any
}

RECTANGLE UltralyticsModel {
    - model_id: str
    - model: Any
    __init__()
    + download(model_id: str): None
    + load(model_id: str): None
    + inference(image_path: str): Any
    + train(data_path: str, epochs: int = 100): Any
}

RECTANGLE WatsonModel {
    - model: Any
    __init__()
}

RECTANGLE Playground {
    - playground_id: str
    - playground_name: str
    - playground_description: str
    - playground_models: List[str]
    - playground_chain: List[str]
    __init__()
}


ModelControl --> TransformerModel : uses
ModelControl --> UltralyticsModel : uses
ModelControl --> WatsonModel : uses
ModelControl --> LibraryControl : uses

PlaygroundControl --> Playground : uses
PlaygroundControl --> ModelControl : uses


' FastAPI --> PlaygroundControl : uses
' FastAPI --> LibraryControl : uses
' FastAPI --> ModelControl : uses
@enduml